-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWfiN5xMET3WTkV2RMORHsGCvofx+1HC4kqvEdxVUFQOgCgYIKoZIzj0DAQehRANCAATdaZSAl9BUo80M0/Q6h0VRGG5gtuPu8VXKT6rocvGepMhXMqNTAFhK/ITXOQCQDiolq23+DxCavtD9ARC7FAHS
-----END PRIVATE KEY-----